export const accounts = [
  "Administration - Church Administration",
  "Administration - Copier/Duplicator",
  "Administration - Outreach Literature/Events",
  "Children's Ministries - Background Checks",
  "Children's Ministries - CE Supplies",
  "Children's Ministries - Childcare",
  "Children's Ministries - Children's Church, 2's and 3's",
  "Children's Ministries - Children's Church, 4 yr and up",
  "Children's Ministries - Children's Sunday School",
  "Children's Ministries - Junior Camp",
  "Children's Ministries - Kid's Connection",
  "Children's Ministries - Nursery",
  "Children's Ministries - Teacher Training",
  "Children's Ministries - VBS",
  "Elders - Special Projects",
  "Elders - Legal Fees",
  "Facilities - Building Security",
  "Facilities - Decorations",
  "Facilities - General Maint/Improvements",
  "Facilities - HVAC Maintenance",
  "Facilities - Janitorial Supplies",
  "Facilities - Property Insurance",
  "Facilities - Special Projects",
  "Facilities - Utilities",
  "Facilities - Vehicle Maintenance",
  "Fellowship - Kitchen & Banquet Supplies",
  "Fellowship - Special Events",
  "Finance - Finance",
  "Men's Ministries - Athletics",
  "Men's Ministries - Chatham Hoops",
  "Men's Ministries - Conferences",
  "Men's Ministries - Quarterly Lunches",
  "Men's Ministries - Social Events & Outreach",
  "Mercy Ministries - Florist",
  "Mercy Ministries - Meals",
  "Missions - Budgeted Missions",
  "Music - Supplies/Equipment",
  "Music - Piano/Instrument Maintenance",
  "Pastoral Ministries - Adult Sunday School",
  "Pastoral Ministries - Communion Elements",
  "Pastoral Ministries - Counseling",
  "Pastoral Ministries - Honorariums",
  "Pastoral Ministries - Small Groups",
  "Pastoral Ministries - Business Exp.-Pastor",
  "Pastoral Ministries - Business Exp.-Youth Pastor",
  "Pastoral Ministries - Worker's Compensation Ins",
  "Technology - AV Equipment",
  "Technology - Communications (website/sermons online)",
  "Technology - Computers/Network",
  "Technology - Projection",
  "Technology - Sound & Lighting",
  "Women's Ministries - Child Care",
  "Women's Ministries - Miscellaneous",
  "Women's Ministries - Special Events",
  "Women's Ministries - Women's Bible Study",
  "Women's Ministries - Women's Conference",
  "Youth Ministries - Camp (Jr & Sr High)",
  "Youth Ministries - Short Term Mission Trips",
  "Youth Ministries - Winterfest",
  "Youth Ministries - Youth (Jr & Sr High)",
];
